require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/factories/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/routes.rb'
    - '**/*.rake'
    - '**/*_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/**/*'

Naming/HeredocDelimiterNaming:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/systems/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
