version: '3.4'

x-app: &app
  image: payment-app-dev:1.0.0
  build:
    context: .
    args:
      RUBY_VERSION: 3.1.2
      BUNDLER_VERSION: 2.3.22
      POSTGRES_MAJOR: 11
      NODE_MAJOR: 16
      YARN_VERSION: 1.21.1
services:
  app:
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432
      REDIS_URL: redis://redis:6379/
      BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEB_CONCURRENCY: 1
      HISTFILE: /app/log/.bash_history
      WEB_HOST: 'https://example.com'
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      FIREBASE_API_KEY: ${REACT_APP_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${REACT_APP_AUTH_DOMAIN}
      FIREBASE_DATABASE_URL: ${REACT_APP_DATABASE_URL}
      FIREBASE_PROJECT_ID: ${REACT_APP_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${REACT_APP_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${REACT_APP_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${REACT_APP_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${REACT_APP_MEASUREMENT_ID}
      COLUMNS: 200
      LINES: 50
      # https://github.com/DatabaseCleaner/database_cleaner#safeguards
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
    depends_on:
      - postgres
      - redis
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - 3000:3000

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  postgres:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:5.0.6-alpine
    volumes:
      - redis:/data
    ports:
      - 16379:6379

volumes:
  rails_cache:
  bundle:
  node_modules:
  packs:
  postgres:
  redis:
